#GPU ID
gpu: 0
world_size: 1
# The name of this exp
name: '20221128_loop_HSV_Stylerewrite_lrdowm5to6_'
ckpt_path: './ckpt/'

# The config file of each experiment
config_path: './config_list/'

# start from where, the default is latest
resume_ckpt: 'C:/Users/wiwiw/subject20220725/ckpt/20221128_loop_HSV_Stylerewrite_lrdowm5to6_/model_last.pth' #'C:/Users/wiwiw/subject20220725/ckpt/places2_20000_GTLC_202200919_HSVremake_midlayers_morelayer_HSV_wo_V/model_last.pth'
resume_D_ckpt: 'C:/Users/wiwiw/subject20220725/ckpt/20221128_loop_HSV_Stylerewrite_lrdowm5to6_/Discriminator_last.pth' #'C:/Users/wiwiw/subject20220725/ckpt/places2_20000_GTLC_202200919_HSVremake_midlayers_morelayer_HSV_wo_V/Discriminator_last.pth'
test_ckpt: 'C:/Users/wiwiw/subject20220725/ckpt/20221128_loop_HSV_Stylerewrite_lrdowm5to6_/model_bestPSNR.pth' #'C:/Users/wiwiw/subject20220725/ckpt/places2_20000_GTLC_20220831_1704_model_concat_Sigmoid_halfCforGandL_n_head8/model_bestPSNR.pth'

# data_path & mask_path should be .txt
data_path: './txt/3060_train_dataset_place2.txt'
mask_path: './txt/3060_train_mask_place2.txt'

# Train
batch_size: 4
train_epoch: 200
weight_decay : 0.1
learning_rate: 0.001
lr_decay : True
lr_min: 1e-6
warmup_epoch : 5  #2epochs
D_learning_rate: 0.001
D_lr_decay : True
D_lr_min: 1e-6
D_warmup_epoch : 2  #2epochs
grad_norm_clip: 1.0
# Loss
Lambda_LD1  : 10  #real
Lambda_LD2  : 10  #fake
Lambda_L1: 10
Lambda_Perceptual: 0.1
Lambda_LG  : 10
Lambda_Style: 250
Lambda_Edge: 10
Lambda_HSV: 10
#Lambda_HSV_edge: 100
Lambda_LHSV: 1

# checkpoint settings
num_workers : 0  # for DataLoader
# Define the size of transformer
n_layer: 2
n_embd: 128
n_head: 8   #8>4
embd_pdrop: 0.0
resid_pdrop: 0.0
attn_pdrop: 0.0
block_size: 32
# Define the siee of RDB
nChannel: 3
nDenselayer: 4
nFeat: 128  # 128
scale: 1
growthRate: 32
# cswin transformer
num_layers: 4
split_size: [4, 8, 16, 32]
head: [2, 4, 8, 16]
dim: 128
loop_time: [8, 4, 2, 1] # 1 2 21 1

# where is the validation set of ImageNet
val_path: './txt/3060_test_dataset_place2.txt'
val_mask_path: 'E:/Place2/strokes/strockes_test_3747_1_60'
test_path: './txt/3060_test_dataset_place2.txt'
test_mask_1~60_path: 'E:/Place2/mask_dataset/color_changed/50+60' #1+10~50+60
save_img_path: 'C:/Users/wiwiw/subject20220725/Place2_3747_50+60/' #'E:/subproject20220725_output/'
image_size: 256

